<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-responsive</name>
   <tag></tag>
   <elementGuidId>5fbc799d-3368-4ee3-9840-5945318b112b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;drawer drawer--left drawer-close darkBG&quot;]/div[3]/main[1]/section[@class=&quot;item&quot;]/section[@class=&quot;topBar affix&quot;]/div[@class=&quot;col-md-6&quot;]/a[@class=&quot;navbar-brand&quot;]/img[@class=&quot;img-responsive&quot;]</value>
   </webElementProperties>
</WebElementEntity>
