<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_drawer-hamburger-icon</name>
   <tag></tag>
   <elementGuidId>6aa58982-c86e-484c-be05-c8b804bf80b8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drawer-hamburger-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;drawer drawer--left drawer-close darkBG&quot;]/div[3]/header[1]/button[@class=&quot;drawer-toggle drawer-hamburger flash&quot;]/span[@class=&quot;drawer-hamburger-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
