<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Drivers</name>
   <tag></tag>
   <elementGuidId>d224da52-3318-467f-9fab-b9dd30530576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;drawer drawer--left darkBG drawer-open&quot;]/div[3]/header[1]/nav[@class=&quot;drawer-nav&quot;]/ul[@class=&quot;drawer-menu&quot;]/li[@class=&quot;drawer-dropdown&quot;]/a[@class=&quot;drawer-menu-item&quot;][count(. | //a[@class = 'drawer-menu-item' and @href = '#' and @data-toggle = 'dropdown' and @role = 'button' and @aria-expanded = 'false' and (text() = '
                        Drivers 
                      ' or . = '
                        Drivers 
                      ')]) = count(//a[@class = 'drawer-menu-item' and @href = '#' and @data-toggle = 'dropdown' and @role = 'button' and @aria-expanded = 'false' and (text() = '
                        Drivers 
                      ' or . = '
                        Drivers 
                      ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drawer-menu-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Drivers 
                      </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;drawer drawer--left darkBG drawer-open&quot;]/div[3]/header[1]/nav[@class=&quot;drawer-nav&quot;]/ul[@class=&quot;drawer-menu&quot;]/li[@class=&quot;drawer-dropdown&quot;]/a[@class=&quot;drawer-menu-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
