<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00ContentPlaceHolder1_4</name>
   <tag></tag>
   <elementGuidId>a92d79dc-b70e-4417-a571-44499c8541a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ContentPlaceHolder1_rbDirectPayroll&quot;)[count(. | //input[@id = 'ContentPlaceHolder1_rbDirectPayroll' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PayrollType' and @value = 'rbDirectPayroll']) = count(//input[@id = 'ContentPlaceHolder1_rbDirectPayroll' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PayrollType' and @value = 'rbDirectPayroll'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rbDirectPayroll</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PayrollType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbDirectPayroll</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rbDirectPayroll&quot;)</value>
   </webElementProperties>
</WebElementEntity>
