<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00ContentPlaceHolder1_6</name>
   <tag></tag>
   <elementGuidId>d74f27c0-310c-41e3-8440-36780a37e1b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ContentPlaceHolder1_btnRegisterDriver&quot;)[count(. | //input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$btnRegisterDriver' and @value = 'Register' and @onclick = 'return saveDriverDetails();' and @id = 'ContentPlaceHolder1_btnRegisterDriver' and @class = 'btn btn-primary btn-register']) = count(//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$btnRegisterDriver' and @value = 'Register' and @onclick = 'return saveDriverDetails();' and @id = 'ContentPlaceHolder1_btnRegisterDriver' and @class = 'btn btn-primary btn-register'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnRegisterDriver</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Register</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return saveDriverDetails();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnRegisterDriver</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-register</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnRegisterDriver&quot;)</value>
   </webElementProperties>
</WebElementEntity>
