<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Out</name>
   <tag></tag>
   <elementGuidId>81c96a09-2312-48a8-9234-001d3a11237d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;lnkLogout&quot;)[count(. | //button[@onclick = concat('__doPostBack(' , &quot;'&quot; , 'ctl00$lnkLogout' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and @id = 'lnkLogout' and @type = 'button' and (text() = 'Sign Out' or . = 'Sign Out')]) = count(//button[@onclick = concat('__doPostBack(' , &quot;'&quot; , 'ctl00$lnkLogout' , &quot;'&quot; , ',' , &quot;'&quot; , '' , &quot;'&quot; , ')') and @id = 'lnkLogout' and @type = 'button' and (text() = 'Sign Out' or . = 'Sign Out')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>__doPostBack('ctl00$lnkLogout','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkLogout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkLogout&quot;)</value>
   </webElementProperties>
</WebElementEntity>
