<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00ContentPlaceHolder1 (2)</name>
   <tag></tag>
   <elementGuidId>05cd01f5-e0d2-4d01-a8bf-2cf6abeb36e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ContentPlaceHolder1_txtInvoiceNumber&quot;)[count(. | //input[@name = 'ctl00$ContentPlaceHolder1$txtInvoiceNumber' and @type = 'text' and @maxlength = '30' and @id = 'ContentPlaceHolder1_txtInvoiceNumber' and @class = 'form-control m-b' and @placeholder = 'e.g. 321654987ZXCVMNB159357' and @title = 'Please enter Invoice Number' and @onkeypress = 'clearErrorMessage();']) = count(//input[@name = 'ctl00$ContentPlaceHolder1$txtInvoiceNumber' and @type = 'text' and @maxlength = '30' and @id = 'ContentPlaceHolder1_txtInvoiceNumber' and @class = 'form-control m-b' and @placeholder = 'e.g. 321654987ZXCVMNB159357' and @title = 'Please enter Invoice Number' and @onkeypress = 'clearErrorMessage();'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtInvoiceNumber</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_txtInvoiceNumber</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control m-b</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 321654987ZXCVMNB159357</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please enter Invoice Number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>clearErrorMessage();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_txtInvoiceNumber&quot;)</value>
   </webElementProperties>
</WebElementEntity>
